export enum ExpenseCategory {
  FOOD = "food",
  TRANSPORT = "transport",
  HOUSING = "housing",
  UTILITIES = "utilities",
  ENTERTAINMENT = "entertainment",
  HEALTH = "health",
  EDUCATION = "education",
  SHOPPING = "shopping",
  SUBSCRIPTIONS = "subscriptions",
  TRAVEL = "travel",
  PERSONAL = "personal",
  GIFTS = "gifts",
  INVESTMENTS = "investments",
  SAVINGS = "savings",
  TAXES = "taxes",
  INSURANCE = "insurance",
  DEBT = "debt",
  OTHER = "other",
}
